### ISSUE TITLE
Development Improvements

### ISSUE THREAD

**Issue by devilankur18** [AamAadmiParty/cleansweep#104]
Suggestions:

- Multiple configuration for differnt environments (development, production, staging etc)
Check yconf pip  for doing so

- Enable logging for all modules so can easily throw debug logs during development

- Enable database related queries and logs so can see query process and do optimizations.

**Comment by anandology** [comment]
Handled the last 2. 

Enabled [Flask-Debug-Toolbar][1] in debug mode and added logger attribute to plugin.

[1]: http://flask-debugtoolbar.readthedocs.org/en/latest/

**Comment by anandology** [comment]
Now we can log using:

    plugin.logger.info("something")

or

    app.logger.info("something")

**Comment by anandology** [comment]
Created new issue #118 for having different configurations. Closing this issue now.
