### ISSUE TITLE
Typos and spelling mistakes

### ISSUE THREAD

**Issue by RaghavPro** [AamAadmiParty/cleansweep#111]
Let's keep one issue open for typos and spelling mistakes. 

<li>In `signups/templates/signup_complete.html`
        "Thank you for signing up as a volunteer. **We've** get back to you shortly."</li>
<li>In `volunteers/templates/add_volunteer.html`
"Please select an assembly **contituency** to continue."</li>

**Comment by anandology** [comment]
Lets fix the typos  as we find them instead of keeping an issue open forever.

**Comment by RaghavPro** [comment]
<li> In `committees/templates/new_committee_structure.html`
Line 14 `<h3>Roles</strong></h3>`</li>


<li> In `committees/templates/new_committee_structure.html`
"No <b>committes</b> are available at {{place.type.name}} level"
</li>
