### ISSUE TITLE
Improve the committee-structure URLs

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#117]
The committee-structure URLs looks a big ugly right now.

    .../committee-structures/PX.pollingcenter-committee

Right now there is unique constraint on committe-slug and place-type and that is causing URLs like that. This is also making downloading members of all committees with same type cumbersome.

We need to change the unique constraint to have just committee-slug (of course with place_id).

Once that is done, the committee-structure URLs need to be fixed. They should have just the slug without the place-type (like `committee-structures/pollingcenter-committee`).

**Comment by RaghavPro** [comment]
I'm a bit unclear on this.
What to do after removing committee level from slug?

And how about `.../committee-structures/PX/pollingcenter-committee`?
Doesn't look that bad to me.

**Comment by anandology** [comment]
We don't want to have the level name in the URL. it should just be `committee-structures/pollingcenter-committee`.

**Comment by RaghavPro** [comment]
What if there are two committees with same slug but at different level?

**Comment by anandology** [comment]
We don't want to allow that by creating place, slug unique index in the db.

**Comment by anandology** [comment]
Thanks @RaghavPro. I've merged the pull-request.
