### ISSUE TITLE
Have different configuration files for production, dev and test

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#118]
The production, dev and test should use `production_settings.py`, `dev_settings.py` and `test_settings.py` respectively.

Related to Development Improvements #104.

**Comment by anandology** [comment]
@devilankur18 and @RaghavPro does this look like a good plan? Do you have any suggestions?

**Comment by anandology** [comment]
haven't heard any inputs, going ahead with the proposed plan.

**Comment by devilankur18** [comment]
@anandology Few suggestions about naming conventions and files

- Place then under directory config/environments /*
- names production.py , development.py testing.py staging.py etc
- Make a file all.py or some other name which should all the common settings across all the environments

**Comment by anandology** [comment]
The default_settings.py can be used for all settings. Also it is possible to do `from common_settings import *` in each settings file. There is no need for any special support.

If want to go a directory to store settings, then we might as well look at the flask's recommended instance folder setup. Somehow I find it confusing. 

Why `config/enviroments/` why not just `settings/` or `config/`? `settings/production.py` or `settings/development.py`.

**Comment by devilankur18** [comment]
@anandology I was mentioning as per the rails standard, but go ahead if there is already a standard in flask for the same.
