### ISSUE TITLE
Make level select tag disabled when editing a committee

### ISSUE THREAD

**Issue by RaghavPro** [AamAadmiParty/cleansweep#122]
![screen shot 2015-09-23 at 14 38 51](https://cloud.githubusercontent.com/assets/4872139/10041282/d8ccb768-6200-11e5-992d-e90f7a6d14d8.png)
Changing a committee level is not allowed. Better make it disable when editing.

**Comment by anandology** [comment]
Changing committee level should be allowed only when no committees are created with that structure.
