### ISSUE TITLE
The home page should redirect to login page on first visit

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#124]
The home page is currently visible to everyone, but they can't do anything. It'll be less confusing to have the home page redirect to the login page.

**Comment by RaghavPro** [comment]
How about redirect to the signup page instead? 
New users sign up and already registered can login from there.

**Comment by anandology** [comment]
Login is most common use case than sign. Please redirect to login page.

On Wednesday Oct 14, 2015 at 8:13 PM, Raghav Sharma <notifications@github.com>, wrote:

How about redirect to the signup page instead? 
New users sign up and already registered can login from there.

---
