### ISSUE TITLE
Ability to select multiple permissions for a committee role

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#127]
We need to implement an ability to select multiple permissions for a role in a committee.

Bootstrap chosen seems like a good UI component to use.
http://jquery-plugins.net/bootstrap-chosen-alternate-stylesheet-for-chosen-with-bootstrap

**Comment by RaghavPro** [comment]
That plugin looks great. I'll create a mockup.

**Comment by anandology** [comment]
Thanks @RaghavPro for the [mockup][1].

[1]: http://test.missionvistaar.in/mockups/new_committee_structure.html

I think we need two improvements here.

1. Have an ALL permission to give every permission
2. Group the permissions by component, something like this:

    All Permissions
    SMS (section)
        send-sms
    VOLUNTEERS (section)
        view-volunteers
        add-volunteer
        download-volunteers
    COMMITTEES (section)
        view-committees
        edit-committees
        download-committee-members

What do you think?

**Comment by RaghavPro** [comment]
Sure, sounds good. I'll update the mockup.

**Comment by anandology** [comment]
This issue is obsolete now. we've implemented permission groups and a role gets mapped to a permission group. see #147 and #148 for more details.
