### ISSUE TITLE
Organize committee structures by level

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#149]
Right now the Admin Center > Committee Structures page provides the list of all committee structures on that page it self. It would be nice to group them by the level. Something like this:

    /admin/committee-structures page

    State Level (1)
    District Level (1)
    AC Level (2)
    Ward Level (1)
    Polling Booth level (1)

The number in the brackets indicates the number of committee structures defined for that level.

Clicking on level link should take to /admin/committee-structures/<level> page, where level will be one of state, dt, ac, ward, px or pb. On that page it should show only the committee structures defined at that level. 

Also, the add committee structure link should be moved to the level page. The changes required on add committee structure will be implemented as part of a separate issue.

**Comment by anandology** [comment]
Thanks for PR @RaghavPro. I think there is some more room for improvement.

Move the "add new committee structure" from /admin/committee-structures page and move it to /admin/committee-structures/at/<level> page. When add-new button is pressed on that page, the level should be automatically selected (or even better, it is not editable or hidden). 

Please try a mockup if the above description is not clear.

**Comment by RaghavPro** [comment]
Yes, I was thinking about something like that. Should I just remove the level selection when creating a new committee?

**Comment by anandology** [comment]
I think that is a good idea.

**Comment by RaghavPro** [comment]
This is done.
