### ISSUE TITLE
Limit the number of characters in SMS

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#158]
We need the ability to limit the number of characters in SMS. Lets put the limit to 200 for now. We'll make it customizable later.

**Comment by charanjeetaap** [comment]
It should be 160 characters. Thats the standard limit of 1 sms.

**Comment by anandology** [comment]
Thanks for pointing that @charanjeetaap. I wasn't aware of that.

**Comment by RaghavPro** [comment]
Done.
