### ISSUE TITLE
Simplify volunteers page

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#161]
Simplify the volunteers page. 

Notable changes:
* contact details are visible on volunteers page now
* search box is provided (search will be implemented later)

[mockup available](http://test.missionvistaar.in/mockups/volunteers.html)

**Comment by RaghavPro** [comment]
>contact details are visible on volunteers page now
What contact details?

**Comment by RaghavPro** [comment]
This is done.
Search was implemented in #162
