### ISSUE TITLE
Added search to volunteers page

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#162]
We already have volunteer search accessible from edit committee pages. Make it available on the volunteers page.

**Comment by RaghavPro** [comment]
Ajax or form?

**Comment by anandology** [comment]
Thanks for the PR, @RaghavPro. Couple of issues I want you to address.

1. search should be GET request, not POST.
2. The search string should be displayed in the search box when displaying the results.
3. Hide the action buttons when showing search results.
4. clearly indicate that these are search results and not entire list of volunteers.

My suggestion for 4 is to display a message like this:

Displaying volunteers matching **"Anand"**. [show all]

**Comment by RaghavPro** [comment]
Sure.

Date: Thu, 4 Feb 2016 04:17:56 -0800

**Comment by anandology** [comment]
Thanks @RaghavPro for doing the improvements in 9e8b4f94ab364fd722ff06919e8ad2849c22c607.

**Comment by anandology** [comment]
Found a bug. 

It is showing only first 10 entries. 

Make the limit to 100 and change the message to "showing first 100 volunteers matching xxx" if the count is 100.

Also I suggest using the query param `q` instead of `search-query`.

**Comment by RaghavPro** [comment]
This is done I think.
