### ISSUE TITLE
Display photo on profile page

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#165]
Display photo of the volunteer from facebook/google on the profile page.

**Comment by RaghavPro** [comment]
Implemented in https://github.com/AamAadmiParty/cleansweep/commit/bec0c450172ad38335ccdff6d5ba595cdd2c5996

![screen shot 2016-04-04 at 23 17 17](https://cloud.githubusercontent.com/assets/4872139/14257652/7783f9a8-fabc-11e5-8362-096d70bbbe36.png)
