### ISSUE TITLE
Improve door2door listing

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#176]
Improve the door2door listing as described below.

* Add a column with label `When` to show the timestmap. Make it the first column. It should show time as "2 minutes ago", "1 day ago" etc for recent entries.
* Make the timestamp a link to door2door/entries/<entry-id> to show the full details about that record. Including all the info in the details field.
* Remove the delete button on entries page and move it to the entry page.

**Comment by RaghavPro** [comment]
It looks better if 'when' is the last column
![screen shot 2016-02-10 at 16 57 00](https://cloud.githubusercontent.com/assets/4872139/12946024/6fb7b658-d017-11e5-9e65-f573ed509b4e.png)
--
![screen shot 2016-02-10 at 16 57 24](https://cloud.githubusercontent.com/assets/4872139/12946027/70accb66-d017-11e5-8b06-eb999feeecfc.png)

**Comment by charanjeetaap** [comment]
Yes it looks better that way.

**Comment by anandology** [comment]
+1

**Comment by RaghavPro** [comment]
Implemented in https://github.com/AamAadmiParty/cleansweep/commit/20f225b1d9ff222dfd2f4664bd9566b4df489154
