### ISSUE TITLE
If I can't see committees it shouldn't be in my list of menu items on left

### ISSUE THREAD

**Issue by zumbl** [AamAadmiParty/cleansweep#179]
<img width="1268" alt="screen shot 2016-03-30 at 2 11 55 am" src="https://cloud.githubusercontent.com/assets/10849284/14123158/d6de13c4-f61c-11e5-92df-2cc802fa788b.png">
<img width="1271" alt="screen shot 2016-03-30 at 2 12 05 am" src="https://cloud.githubusercontent.com/assets/10849284/14123159/d6e47430-f61c-11e5-9147-4c9bed9a572b.png">

**Comment by RaghavPro** [comment]
Fixed.
