### ISSUE TITLE
Design user dashboard

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#46]
Comeup with a mock up for user dashboard. The dashboard should provide quick access to all the things that a user can do with the system. It should probably change based on his role and permissions.

**Comment by anandology** [comment]
@devilankur18 could you start thinking about what to display in dashboard?

One thing that we should add for sure is list of committees he is part of.

**Comment by charanjeetaap** [comment]
a volunteer will be part of only one committee at a time..

**Comment by anandology** [comment]
I think we are something better now and in the right direction. `mockups/dashboard.html` has a mockup of what we want to achieve. We'll improve this as we go along. We no longer need a separate issue for this. Closing this issue.
