### ISSUE TITLE
A problem in validation check if both voterid and place_id fields are None

### ISSUE THREAD

**Issue by RaghavPro** [AamAadmiParty/cleansweep#54]
`Forms.py` for signup
`if not self.voterid.data and not self.place.data:`

This statement does not qualify if both are empty because `place.data` is of type `unicode` and not `NoneType`.

The condition fails and you get an Integrity error that `place_id` is null in `pending_member`

**Comment by anandology** [comment]
The UI for adding members and signup is going to change a bit now. Lets wait on this for a day or two.
