### ISSUE TITLE
Fix the configuration file.

### ISSUE THREAD

**Issue by RaghavPro** [AamAadmiParty/cleansweep#55]
Another little one.
The `init` method creates `production.cfg` and writes `ADMINS` property. 
But the `get_permissions` method looks for `ADMIN_USERS`. So, change any one of them. 

And also make it write `VOTERDB_URL` in `init`.

**Comment by anandology** [comment]
voterdb issue is another mess. Lets deal with that separately.

**Comment by anandology** [comment]
fixed the ADMIN_USERS issue.
