### ISSUE TITLE
Add volunteer form

### ISSUE THREAD

**Issue by charanjeetaap** [AamAadmiParty/cleansweep#57]
Mobile number should be mandatory instead of booth number.

**Comment by devilankur18** [comment]
@anandology I was working on this issue. I have made the changes as mentioned, but there is issue related to the null booth number. As per the schema, its has a foreign key constraint, which doesnot allow null booth as there is not a null value.

I was thinking of adding a new place called not-assigned so by default everyone who dont have any pb can be automatically assigned to it. 

This issue is also related to the  https://github.com/anandology/cleansweep/issues/52

**Comment by anandology** [comment]
I think phone number is already mandatory.

The idea is to have a booth "Not specified" with value "" and add the
volunteer to the place directly. That'll allow adding a volunteer to an AC
or a ward.

We also need a configuration to decide which all types allow adding
volunteers. I think the plan is to allow adding volunteers at AC level and
below.



On Sun, Jul 19, 2015 at 12:35 PM, Ankur Agarwal <notifications@github.com>
wrote:

> @anandology <https://github.com/anandology> I was working on this issue.
> I have made the changes as mentioned, but there is issue related to the
> null booth number. As per the schema, its has a foreign key constraint,
> which doesnot allow null booth as there is not a null value.
>
> I was thinking of adding a new place called not-assigned so by default
> everyone who dont have any pb can be automatically assigned to it.
>
> This issue is also related to the #52
> <https://github.com/anandology/cleansweep/issues/52>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/anandology/cleansweep/issues/57#issuecomment-122634163>
> .
>



-- 
Anand
http://anandology.com/

**Comment by devilankur18** [comment]
As per the code, phone number is not mandatory. Neither in the form, it has required validations. I enforced in the form validations to make it required.


    place_id = db.Column(db.Integer, db.ForeignKey('place.id'))
    place = db.relationship('Place', backref=db.backref('members', lazy='dynamic'))
    name = db.Column(db.Text, nullable=False)
    email = db.Column(db.Text, unique=True)
    phone = db.Column(db.Text)
    voterid = db.Column(db.Text)
    details = db.Column(JSON)
    created = db.Column(db.DateTime, default=datetime.datetime.now)


I am not very clear on it.

**Comment by anandology** [comment]
Great, Thanks!

**Comment by devilankur18** [comment]
Here are my changes https://github.com/devilankur18/cleansweep/commit/6eb2d94ecf4a24813323faa2765f9ffb8f5d82e5

Still not able to create a new record due to the foreign key constraint. I we add a place to the db with name "Not specified" and value  "0", should it be ok ?

**Comment by anandology** [comment]
No, just add it the current place. 

If you are trying to add volunteer from AC page, then add the volunteer directly to the AC page.

**Comment by devilankur18** [comment]
@anandology please review the pull request

**Comment by devilankur18** [comment]
@anandology updated as per suggestions, please review again.

**Comment by devilankur18** [comment]
@anandology please close if finished

**Comment by anandology** [comment]
Fixed.

**Comment by charanjeetaap** [comment]
Is this done? bcoz i still have to select a booth to enter a volunteer record.

**Comment by anandology** [comment]
Sorry, I forgot to deploy the changes.

**Comment by anandology** [comment]
try now. It shows the AC name/Ward name as well. I think better to show "I Don't know" or something.

**Comment by charanjeetaap** [comment]
but will it put AC/Ward name into the polling booth column or it will go into a seperate column?

**Comment by charanjeetaap** [comment]
it should only take a proper 10 digit number as phone number

**Comment by charanjeetaap** [comment]
are we also applying the duplicate phone number check here..?

**Comment by anandology** [comment]
@devilankur18 could you please add the 10 digit and uniqueness check?

**Comment by devilankur18** [comment]
Consolidating
- Phone number validations, 10 digit or with international code ?
- Validation for Duplicates


@anandology Is that all ?

**Comment by anandology** [comment]
No international numbers for now. Remove the spaces in the phone number before checking for 10 digits. 

It would be good if we can add a help message in the form so that people will try to enter 10 digits only. Not sure how simple it is.

**Comment by charanjeetaap** [comment]
Also i suggest we should put OTP confirmation. Later on, if not now. That
saves us from the junk data.

Or we can do it in stages, like first let the person enter the phone number
and email id but we will only consider them as credible contact information
once they verify it through OTP and email verification.

Can we do this?

Charanjeet Singh
AAP IT team
+91-8588833533

**Comment by anandology** [comment]
Fixed. 

We'll look at OTP issue later.

**Comment by charanjeetaap** [comment]
i still have to select assembly before add volunteer form appears, why is that?

**Comment by anandology** [comment]
As of now there is no way to add a volunteer to a state. I'll create a separate issue for that. Closing this...
