### ISSUE TITLE
Migration Flow

### ISSUE THREAD

**Issue by devilankur18** [AamAadmiParty/cleansweep#67]
For changing db structure setup migration flow 

https://sqlalchemy-migrate.readthedocs.org/en/latest/versioning.html#project-setup

**Comment by anandology** [comment]
I think sqlchemy-migrate is not maintained anymore, try alembic.

https://alembic.readthedocs.org/en/latest/tutorial.html

**Comment by anandology** [comment]
Lets start using [Flask-Script][1] and [Flask-Migrate][2].

[1]: http://flask-script.readthedocs.org/
[2]: http://flask-migrate.readthedocs.org/en/latest/

**Comment by anandology** [comment]
I think it is important to get this done first as other tasks like marking phone number/email verified requires this functionality.

**Comment by devilankur18** [comment]
@anandology I have pushed my changes on migration branch. There is not much done, you can choose to start from scratch as well.
