### ISSUE TITLE
Ability to download committees

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#79]
Provide ability to download members of all committees at once.

It should have the following columns.

* Committee name
* Role 
* Member Name
* Member Email
* Member Phone

Open Questions:

Will there be interest to download all members of all committees at once? There are three possible options.

* Download all members of all committees at all levels
* Download all members of all committees at one level (say download all committee members at ward level)
* Download all members of all committees at with given name/slug (say download all members of "Ward Action Committee" of all wards in Delhi)

Which one shall we implement?

@charanjeetaap please add your inputs

**Comment by charanjeetaap** [comment]
let me give you an example, a person will be requiring to download the data of like

In the "Same Leg" of the hierarchy:

all booth incharges below his level
all polling station incharges below his level
all ward incharges below his level (for levels above ward level)
all ward treasurers below his level
all assembly incharges below his level
all assembly treasurers below his level

that is the logic we will follow

**Comment by charanjeetaap** [comment]
This issue is still open, its of Alpha..

**Comment by anandology** [comment]
Oops, I've wrongly tagged all the commits as issse #99.

**Comment by anandology** [comment]
Sent a pull request #107 implementing this.

**Comment by anandology** [comment]
Done, merged the pull request.

The option to download all the members of a committee is available from:
http://test.missionvistaar.in/DL/committees/explore
