### ISSUE TITLE
Implement permission system

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#87]
We need a system to easily handle different access controls in the system. The idea is to have different permissions like `send-sms`, `add-volunteer` etc. and map them to roles like `coordinator of it-admins committee`. The whole thing gets even more interesting because we have another dimension of location hierarchy.

**Comment by charanjeetaap** [comment]
this is very much required now, as anybody with a login and write permission is able to edit anything in the system from state level to any level..

**Comment by anandology** [comment]
That is not true. permission is tied to a location. If a person has write permission at an AC, he can modify only inside his own AC, not entire state. Similarly, we make someone a ward coordinator, he gets write permission for his ward and he can modify stuff in his ward, not elsewhere.

**Comment by anandology** [comment]
This is done now. We have permissions and permission groups and they can be attached to roles of a committee. While there is still room for improvement, the current situation is good enough for sometime.

See #147 to know more about permission groups.
