### ISSUE TITLE
Add support for microsoft login

### ISSUE THREAD

**Issue by anandology** [AamAadmiParty/cleansweep#93]
We have support for login using google and facebook. Lets add Microsoft login as well.

**Comment by RaghavPro** [comment]
I'm doing this.

Can you register the application?
https://account.live.com/developers/applications

**Comment by anandology** [comment]
Live in production now. Thanks @RaghavPro.

Could you please make sure we only ask for `wl.email` permission. I don't think we need `wl.basic` which includes contacts lists etc.

**Comment by anandology** [comment]
@RaghavPro could you please fix this?

**Comment by RaghavPro** [comment]
All right. Give me a second.
________________________________
